version: 2

models:
  - name: silver_sales
    description: "Cleaned, deduplicated sales data from raw sources, ready for analytics."
    columns:
      - name: Quantity
        description: "Number of units sold in this transaction."
        tests:
          - not_null
          - positive_quantity

      - name: Total_Amount
        description: "Total monetary amount for the sale transaction."
        tests:
          - not_null
          - positive_total_amount

      - name: Sale_ID
        description: "Unique identifier for a sale transaction."
        tests:
          - not_null

      - name: Product_ID
        description: "References the unique product sold."
        tests:
          - not_null
          - relationships:
              to: ref('silver_products')
              field: Product_ID

      - name: Store_ID
        tests:
          - relationships:
              to: ref('silver_stores')
              field: Store_ID
