-- =====================================================================
-- Model: top_5_products_by_revenue
-- Description:
--   This gold model calculates the total revenue generated by each 
--   product and ranks them in descending order. It then filters the 
--   results to return only the top 5 highest-revenue products.
--
-- Source Tables:
--   - silver_sales (contains product-level sales transactions)
--
-- Output:
--   - Product_ID
--   - revenue (total money generated)
--   - revenue_rank (1 = highest revenue)
-- =====================================================================

{{ config(
    materialized = 'table',
    schema = 'retail_gold',
    alias = 'top_5_products_by_revenue',
    tags = ['gold', 'sales', 'ranking']
) }}

-- ============================================================
-- Step 1: Aggregate revenue by Product_ID
-- ============================================================
with product_revenue as (
    select
        s.Product_ID as Product_ID,
        sum(s.Total_Amount) as revenue   -- Total revenue for each product
    from {{ ref('silver_sales') }} s
    group by s.Product_ID
),

-- ============================================================
-- Step 2: Rank products by revenue (highest revenue = rank 1)
-- ============================================================
ranked_products as (
    select
        Product_ID,
        revenue,
        rank() over (order by revenue desc) as revenue_rank
    from product_revenue
)

-- ============================================================
-- Step 3: Select only the top 5 products
-- ============================================================
select
    Product_ID,
    revenue,
    revenue_rank
from ranked_products
where revenue_rank <= 5
order by revenue_rank
